// Type definitions for carbon-pictograms-svelte
// 598 pictograms from @carbon/pictograms@10.15.0

declare class Pictogram {
  $$prop_def: {
    /** @type {string} [id] */
    id?: string;

    /** @type {string} [class] */
    class?: string;

    /** @type {string} [tabindex] */
    tabindex?: string;

    /** @type {boolean} [focusable] */
    focusable?: boolean;

    /** @type {string} [title] */
    title?: string;

    /** @type {string} [style] */
    style?: string;

    /**
     * Fill color
     * @type {string} [fill="#161616"]
     */
    fill?: string;

    /**
     * Stroke color
     * @type {string} [stroke=currentColor]
     */
    stroke?: string;

    /** @type {string} [width="48"] */
    width?: string;

    /** @type {string} [height"48"] */
    height?: string;
  };

  $$slot_def: {
    /** @type {{}} [default] */
    default?: {};
  };
}
export class ActiveServer extends Pictogram {}
export class AddDevice extends Pictogram {}
export class AddDocument extends Pictogram {}
export class Advocate extends Pictogram {}
export class Agriculture extends Pictogram {}
export class AirConditioner extends Pictogram {}
export class Airplane extends Pictogram {}
export class Alarm extends Pictogram {}
export class AlchemyDataNews extends Pictogram {}
export class AlchemyLanguage extends Pictogram {}
export class AlchemyLanguageAlphabetAExpanded extends Pictogram {}
export class AlchemyVision extends Pictogram {}
export class Americas extends Pictogram {}
export class AmsterdamCanal extends Pictogram {}
export class AmsterdamFarm extends Pictogram {}
export class AmsterdamWindmill extends Pictogram {}
export class Analyze extends Pictogram {}
export class AnalyzesData extends Pictogram {}
export class Apartment extends Pictogram {}
export class Api extends Pictogram {}
export class AppDeveloper extends Pictogram {}
export class Apple extends Pictogram {}
export class Application extends Pictogram {}
export class Archive extends Pictogram {}
export class AsiaAustralia extends Pictogram {}
export class AugmentedReality extends Pictogram {}
export class Austin extends Pictogram {}
export class AutomateModularManagement extends Pictogram {}
export class AutomationDecision extends Pictogram {}
export class Automobile extends Pictogram {}
export class Backpack extends Pictogram {}
export class Bag extends Pictogram {}
export class Bangalore extends Pictogram {}
export class Bee extends Pictogram {}
export class BeijingMunicipal extends Pictogram {}
export class BeijingTower extends Pictogram {}
export class BerlinBrandenburg extends Pictogram {}
export class BerlinBrandenburgGate extends Pictogram {}
export class BerlinCathedral extends Pictogram {}
export class BerlinTower extends Pictogram {}
export class Bicycle extends Pictogram {}
export class Blender extends Pictogram {}
export class Blockchain extends Pictogram {}
export class BoxPlot extends Pictogram {}
export class Build extends Pictogram {}
export class Building extends Pictogram {}
export class Bulldozer extends Pictogram {}
export class Bus extends Pictogram {}
export class Cafe extends Pictogram {}
export class Calendar extends Pictogram {}
export class CalendarDate extends Pictogram {}
export class CalendarEvent extends Pictogram {}
export class Camera extends Pictogram {}
export class Capitol extends Pictogram {}
export class Care extends Pictogram {}
export class CargoCrane extends Pictogram {}
export class CargoShip extends Pictogram {}
export class Cell extends Pictogram {}
export class Chart_3D extends Pictogram {}
export class ChartArea extends Pictogram {}
export class ChartBar extends Pictogram {}
export class ChartBubble extends Pictogram {}
export class ChartBubbleLine extends Pictogram {}
export class ChartCandlestick extends Pictogram {}
export class ChartCustom extends Pictogram {}
export class ChartErrorBar extends Pictogram {}
export class ChartEvaluation extends Pictogram {}
export class ChartHighLow extends Pictogram {}
export class ChartHistogram extends Pictogram {}
export class ChartLine extends Pictogram {}
export class ChartMultiLine extends Pictogram {}
export class ChartMultiType extends Pictogram {}
export class ChartParallel extends Pictogram {}
export class ChartPie extends Pictogram {}
export class ChartRadar extends Pictogram {}
export class ChartRiver extends Pictogram {}
export class ChartScatterplot extends Pictogram {}
export class ChartStepper extends Pictogram {}
export class ChartSunburst extends Pictogram {}
export class ChartTSne extends Pictogram {}
export class Cheese extends Pictogram {}
export class Cherries extends Pictogram {}
export class ChipCircuit extends Pictogram {}
export class ChipCredit extends Pictogram {}
export class ChipDebit extends Pictogram {}
export class CirclePacking extends Pictogram {}
export class ClientFinancing_01 extends Pictogram {}
export class ClientFinancing_02 extends Pictogram {}
export class ClothesRack_01 extends Pictogram {}
export class ClothesRack_02 extends Pictogram {}
export class CloudAnalytics extends Pictogram {}
export class CloudAssets extends Pictogram {}
export class CloudBuilderProfessionalServices extends Pictogram {}
export class CloudComputing extends Pictogram {}
export class CloudDataServices extends Pictogram {}
export class CloudDownload extends Pictogram {}
export class CloudEcosystem extends Pictogram {}
export class CloudGuidelines extends Pictogram {}
export class CloudManagedServices extends Pictogram {}
export class CloudOracle extends Pictogram {}
export class CloudPartners extends Pictogram {}
export class CloudPlanning extends Pictogram {}
export class CloudSap extends Pictogram {}
export class CloudServices extends Pictogram {}
export class CloudServicesPricing extends Pictogram {}
export class CloudStorage extends Pictogram {}
export class CloudStrategy extends Pictogram {}
export class CloudTutorials extends Pictogram {}
export class CloudUpload extends Pictogram {}
export class CloudVmware extends Pictogram {}
export class Cloudy extends Pictogram {}
export class CloudyDewy extends Pictogram {}
export class CloudyHazy extends Pictogram {}
export class CloudyHumid extends Pictogram {}
export class CloudyPartial extends Pictogram {}
export class CloudyWindy extends Pictogram {}
export class CoatHanger extends Pictogram {}
export class CodeSyntax extends Pictogram {}
export class CognosAnalytics extends Pictogram {}
export class College extends Pictogram {}
export class CommercialFinancing_01 extends Pictogram {}
export class CommercialFinancing_02 extends Pictogram {}
export class ConceptExpansion extends Pictogram {}
export class ConceptInsights extends Pictogram {}
export class Connect extends Pictogram {}
export class ConnectedEcosystem extends Pictogram {}
export class ConnectedNodesToTheCloud extends Pictogram {}
export class Console extends Pictogram {}
export class ConsoleWireless extends Pictogram {}
export class Construct extends Pictogram {}
export class ConsumerEngagementFoodJourney extends Pictogram {}
export class Contract extends Pictogram {}
export class Conversation extends Pictogram {}
export class CopenhagenPlanetarium extends Pictogram {}
export class CopenhagenSnekkja extends Pictogram {}
export class Coronavirus extends Pictogram {}
export class CreditCard extends Pictogram {}
export class Crop extends Pictogram {}
export class CustomerService extends Pictogram {}
export class DataBackup extends Pictogram {}
export class DataInsights extends Pictogram {}
export class DataProcessing extends Pictogram {}
export class DataSet extends Pictogram {}
export class DataStorage extends Pictogram {}
export class Delete extends Pictogram {}
export class DeliverInsights extends Pictogram {}
export class DeliveryTruck extends Pictogram {}
export class DesignAndDevelopment_01 extends Pictogram {}
export class DesignAndDevelopment_02 extends Pictogram {}
export class DesignThinkingTeam extends Pictogram {}
export class Desktop extends Pictogram {}
export class DeveloperZOs extends Pictogram {}
export class Devops extends Pictogram {}
export class Dialogue extends Pictogram {}
export class Digital extends Pictogram {}
export class Dining extends Pictogram {}
export class DistributionLedger extends Pictogram {}
export class Dna extends Pictogram {}
export class DoNot extends Pictogram {}
export class Docker extends Pictogram {}
export class Doctor extends Pictogram {}
export class DocumentConversion extends Pictogram {}
export class DocumentSecurity extends Pictogram {}
export class DoorHandle extends Pictogram {}
export class Download extends Pictogram {}
export class DownloadAlt extends Pictogram {}
export class DubaiPalmIslands extends Pictogram {}
export class DubaiSkyscraper extends Pictogram {}
export class DublinBrewery extends Pictogram {}
export class DublinCastle extends Pictogram {}
export class DuplicateFile extends Pictogram {}
export class Education extends Pictogram {}
export class Electric extends Pictogram {}
export class ElectricCar extends Pictogram {}
export class ElectricCharge extends Pictogram {}
export class Elevator extends Pictogram {}
export class Embed extends Pictogram {}
export class EmployeeInsights extends Pictogram {}
export class Engine extends Pictogram {}
export class EnterpriseDesignThinking extends Pictogram {}
export class EnterpriseDesignThinkingAlt extends Pictogram {}
export class Envelope extends Pictogram {}
export class ErlenmeyerFlask extends Pictogram {}
export class EscalatorDown extends Pictogram {}
export class EscalatorUp extends Pictogram {}
export class EuropeAfrica extends Pictogram {}
export class ExpandHorz extends Pictogram {}
export class ExpandUser extends Pictogram {}
export class ExpandVert extends Pictogram {}
export class Export extends Pictogram {}
export class ExportAlt extends Pictogram {}
export class Eye extends Pictogram {}
export class FaceDissatisfied extends Pictogram {}
export class FaceNeutral extends Pictogram {}
export class FaceSatisfied extends Pictogram {}
export class FaceVeryDissatisfied extends Pictogram {}
export class FaceVerySatisfied extends Pictogram {}
export class Factory extends Pictogram {}
export class Farm extends Pictogram {}
export class Farm_01 extends Pictogram {}
export class Farm_02 extends Pictogram {}
export class Farmer_01 extends Pictogram {}
export class Farmer_02 extends Pictogram {}
export class Faucet extends Pictogram {}
export class Feedback extends Pictogram {}
export class Feedback_02 extends Pictogram {}
export class FileBackup extends Pictogram {}
export class FileTransfer extends Pictogram {}
export class FinanceStrategy extends Pictogram {}
export class FinancialConsultant extends Pictogram {}
export class FinancialGain extends Pictogram {}
export class FinancialNetworks extends Pictogram {}
export class FinancialNews extends Pictogram {}
export class FireAlarm extends Pictogram {}
export class FireExtinguisher extends Pictogram {}
export class Firewall extends Pictogram {}
export class FirstAid extends Pictogram {}
export class FlowChart extends Pictogram {}
export class FlowChartDetail extends Pictogram {}
export class Flower_01 extends Pictogram {}
export class Flower_02 extends Pictogram {}
export class Fog extends Pictogram {}
export class Folder extends Pictogram {}
export class Forklift extends Pictogram {}
export class FreeTrial extends Pictogram {}
export class Fuel extends Pictogram {}
export class Gear extends Pictogram {}
export class Gift extends Pictogram {}
export class GlobalAnalytics extends Pictogram {}
export class GlobalAssetsAndRecovery_01 extends Pictogram {}
export class GlobalAssetsAndRecovery_02 extends Pictogram {}
export class GlobalBusinessServices extends Pictogram {}
export class GlobalCurrency extends Pictogram {}
export class GlobalExchange extends Pictogram {}
export class GlobalFinanceEuro extends Pictogram {}
export class GlobalFinanceNetwork extends Pictogram {}
export class GlobalFinanceSterling extends Pictogram {}
export class GlobalMarkets extends Pictogram {}
export class GlobalMarketsBar extends Pictogram {}
export class GlobalNetwork extends Pictogram {}
export class GlobalPartner extends Pictogram {}
export class GlobalSecurity extends Pictogram {}
export class GlobalStrategy extends Pictogram {}
export class GlobalTechnologyServices extends Pictogram {}
export class Globe extends Pictogram {}
export class GlobeLocations extends Pictogram {}
export class Goals extends Pictogram {}
export class Group extends Pictogram {}
export class Growth extends Pictogram {}
export class Hail extends Pictogram {}
export class HailHeavy extends Pictogram {}
export class HailMixed extends Pictogram {}
export class Handicap extends Pictogram {}
export class HandicapActive extends Pictogram {}
export class HardDrive extends Pictogram {}
export class HardDriveNetwork extends Pictogram {}
export class HardIceCream extends Pictogram {}
export class Hazy extends Pictogram {}
export class Headphones extends Pictogram {}
export class Heart extends Pictogram {}
export class HeartHealth extends Pictogram {}
export class HeatMap extends Pictogram {}
export class HeatMap_02 extends Pictogram {}
export class HighFive extends Pictogram {}
export class Hills extends Pictogram {}
export class HomeFront extends Pictogram {}
export class HomeGarage extends Pictogram {}
export class HomeProfile extends Pictogram {}
export class Hospital extends Pictogram {}
export class Humid extends Pictogram {}
export class Hurricane extends Pictogram {}
export class HybridCloud extends Pictogram {}
export class HybridCloudServices extends Pictogram {}
export class IbmIx extends Pictogram {}
export class IbmZ extends Pictogram {}
export class IdBadge extends Pictogram {}
export class Idea extends Pictogram {}
export class Ideate extends Pictogram {}
export class Innovate extends Pictogram {}
export class Insights extends Pictogram {}
export class InspectData extends Pictogram {}
export class Integration extends Pictogram {}
export class Intelligence extends Pictogram {}
export class Intercom extends Pictogram {}
export class IotMunich extends Pictogram {}
export class Java extends Pictogram {}
export class Javascript extends Pictogram {}
export class Justice extends Pictogram {}
export class KeyUsers extends Pictogram {}
export class KnowsDarkData extends Pictogram {}
export class Language extends Pictogram {}
export class Language_01 extends Pictogram {}
export class Language_02 extends Pictogram {}
export class Language_03 extends Pictogram {}
export class Language_04 extends Pictogram {}
export class LanguageTranslation extends Pictogram {}
export class LanguageTranslationAlphabetAExpanded extends Pictogram {}
export class Launch extends Pictogram {}
export class Lightning extends Pictogram {}
export class ListBullet extends Pictogram {}
export class ListCheckbox extends Pictogram {}
export class Location extends Pictogram {}
export class Lock extends Pictogram {}
export class LockAlt extends Pictogram {}
export class LockedNetwork extends Pictogram {}
export class LockedNetworkAlt extends Pictogram {}
export class London extends Pictogram {}
export class LondonBigBen extends Pictogram {}
export class LondonExpandedBase extends Pictogram {}
export class Lungs extends Pictogram {}
export class MachineLearning_01 extends Pictogram {}
export class MachineLearning_02 extends Pictogram {}
export class MachineLearning_03 extends Pictogram {}
export class MachineLearning_04 extends Pictogram {}
export class MachineLearning_05 extends Pictogram {}
export class MachineLearning_06 extends Pictogram {}
export class MadridCathedral extends Pictogram {}
export class MadridSkyscrapers extends Pictogram {}
export class MadridStatue extends Pictogram {}
export class Magnify extends Pictogram {}
export class ManagingContractualFlow extends Pictogram {}
export class ManagingItems extends Pictogram {}
export class Marketplace extends Pictogram {}
export class Mas extends Pictogram {}
export class MathCurve extends Pictogram {}
export class Maximize extends Pictogram {}
export class Medical extends Pictogram {}
export class MedicalCharts extends Pictogram {}
export class MedicalStaff extends Pictogram {}
export class Melbourne extends Pictogram {}
export class Meter extends Pictogram {}
export class MexicoCityAngelOfIndependence extends Pictogram {}
export class MexicoCityMuseoSoumaya extends Pictogram {}
export class Microorganisms extends Pictogram {}
export class Microscope extends Pictogram {}
export class MilanDuomoDiMilano extends Pictogram {}
export class MilanSkyscrapers extends Pictogram {}
export class Minimize extends Pictogram {}
export class MobileAdd extends Pictogram {}
export class MobileChat extends Pictogram {}
export class MobileDevices extends Pictogram {}
export class MobilePhone extends Pictogram {}
export class MonitoredItemOnConveyor extends Pictogram {}
export class MortarAndPestle extends Pictogram {}
export class Moscow extends Pictogram {}
export class MovementInOverlappingNetworks extends Pictogram {}
export class MovementOfGoods_01 extends Pictogram {}
export class MovementOfGoods_02 extends Pictogram {}
export class MovementOfGoods_03 extends Pictogram {}
export class MovementOfItems extends Pictogram {}
export class Mqa extends Pictogram {}
export class Mri extends Pictogram {}
export class MriPatient extends Pictogram {}
export class Multitask extends Pictogram {}
export class Munich extends Pictogram {}
export class NaturalLanguageClassifier extends Pictogram {}
export class NaturalLanguageUnderstanding extends Pictogram {}
export class Network extends Pictogram {}
export class NetworkServices extends Pictogram {}
export class Networking_01 extends Pictogram {}
export class Networking_02 extends Pictogram {}
export class Networking_03 extends Pictogram {}
export class Networking_04 extends Pictogram {}
export class Networking_05 extends Pictogram {}
export class Networking_06 extends Pictogram {}
export class Nice extends Pictogram {}
export class NightClear extends Pictogram {}
export class NycBrooklyn extends Pictogram {}
export class NycManhattan extends Pictogram {}
export class NycManhattanAlt extends Pictogram {}
export class Office extends Pictogram {}
export class OilPump extends Pictogram {}
export class OilRig extends Pictogram {}
export class OptimizeCashFlow_01 extends Pictogram {}
export class OptimizeCashFlow_02 extends Pictogram {}
export class Overcast extends Pictogram {}
export class PaperClip extends Pictogram {}
export class Parliament extends Pictogram {}
export class PartnerRelationship extends Pictogram {}
export class Path extends Pictogram {}
export class Pattern extends Pictogram {}
export class Perfume extends Pictogram {}
export class Person_01 extends Pictogram {}
export class Person_02 extends Pictogram {}
export class Person_03 extends Pictogram {}
export class Person_04 extends Pictogram {}
export class Person_05 extends Pictogram {}
export class Person_06 extends Pictogram {}
export class Person_07 extends Pictogram {}
export class Person_08 extends Pictogram {}
export class Person_09 extends Pictogram {}
export class PersonalityInsights extends Pictogram {}
export class PetriCulture extends Pictogram {}
export class PillBottle_01 extends Pictogram {}
export class Pills extends Pictogram {}
export class PlanningAnalytics extends Pictogram {}
export class PlayerFlow extends Pictogram {}
export class Podcast extends Pictogram {}
export class Police extends Pictogram {}
export class PopulationDiagram extends Pictogram {}
export class Power extends Pictogram {}
export class Pregnant extends Pictogram {}
export class Presentation extends Pictogram {}
export class Presenter extends Pictogram {}
export class Price extends Pictogram {}
export class Printer extends Pictogram {}
export class PrivateNetwork extends Pictogram {}
export class PrivateNetwork_01 extends Pictogram {}
export class PrivateNetworkAlt extends Pictogram {}
export class PrivateNetworkAlt_01 extends Pictogram {}
export class Process extends Pictogram {}
export class Progress extends Pictogram {}
export class Puzzle extends Pictogram {}
export class QQPlot extends Pictogram {}
export class QrCode extends Pictogram {}
export class Question extends Pictogram {}
export class QuestionAndAnswer extends Pictogram {}
export class Racetrack extends Pictogram {}
export class Rainy extends Pictogram {}
export class RainyHeavy extends Pictogram {}
export class Rank extends Pictogram {}
export class Receipt extends Pictogram {}
export class Recycle extends Pictogram {}
export class Refinery extends Pictogram {}
export class Refresh extends Pictogram {}
export class RelationshipExtraction extends Pictogram {}
export class RelationshipDiagram extends Pictogram {}
export class Renew extends Pictogram {}
export class RenewTeam extends Pictogram {}
export class Repeat extends Pictogram {}
export class Report extends Pictogram {}
export class Research extends Pictogram {}
export class Reset extends Pictogram {}
export class ResetHybridCloud extends Pictogram {}
export class ResetSettings extends Pictogram {}
export class RetrieveAndRank extends Pictogram {}
export class RichTextFormat extends Pictogram {}
export class Robot extends Pictogram {}
export class Robotics extends Pictogram {}
export class Rome extends Pictogram {}
export class SaasEnablement extends Pictogram {}
export class SampleFile extends Pictogram {}
export class SanFrancisco extends Pictogram {}
export class SanFranciscoFog extends Pictogram {}
export class SaoPaulo extends Pictogram {}
export class SaoPauloExpandedBase extends Pictogram {}
export class Satellite extends Pictogram {}
export class SatelliteDish extends Pictogram {}
export class Scale extends Pictogram {}
export class ScatterMatrix extends Pictogram {}
export class Seattle extends Pictogram {}
export class SecureData extends Pictogram {}
export class SecureProfile extends Pictogram {}
export class Security extends Pictogram {}
export class SecurityShield extends Pictogram {}
export class ServerRack extends Pictogram {}
export class Servers extends Pictogram {}
export class Shirt extends Pictogram {}
export class Shop extends Pictogram {}
export class ShoppingCart extends Pictogram {}
export class Shower extends Pictogram {}
export class Singapore extends Pictogram {}
export class SingleSignOn extends Pictogram {}
export class Slider extends Pictogram {}
export class Sneaker extends Pictogram {}
export class Snow extends Pictogram {}
export class Socks extends Pictogram {}
export class SoftIceCream extends Pictogram {}
export class SoftlayerEnablement extends Pictogram {}
export class SolarField extends Pictogram {}
export class SolarPanel extends Pictogram {}
export class Solve extends Pictogram {}
export class Spaceship extends Pictogram {}
export class Speech extends Pictogram {}
export class SpeechAlphabetAExpanded extends Pictogram {}
export class SpeechToText extends Pictogram {}
export class Speedometer extends Pictogram {}
export class Sports extends Pictogram {}
export class StairsPlanView extends Pictogram {}
export class StationaryBicycle extends Pictogram {}
export class Steel extends Pictogram {}
export class SteeringWheel extends Pictogram {}
export class StemLeafPlot extends Pictogram {}
export class Stethoscope extends Pictogram {}
export class Strategy extends Pictogram {}
export class StrategyDirect extends Pictogram {}
export class StrategyMove extends Pictogram {}
export class StrategyPlay extends Pictogram {}
export class Streamline extends Pictogram {}
export class Summit extends Pictogram {}
export class Sunny extends Pictogram {}
export class SunnyHazy extends Pictogram {}
export class SupplyChainOptimization_01 extends Pictogram {}
export class SupplyChainOptimization_02 extends Pictogram {}
export class SupportServices extends Pictogram {}
export class SwipeLeft extends Pictogram {}
export class SwipeRight extends Pictogram {}
export class SystemsDevopsAnalyze extends Pictogram {}
export class SystemsDevopsBuild extends Pictogram {}
export class SystemsDevopsCicdPipeline extends Pictogram {}
export class SystemsDevopsCode extends Pictogram {}
export class SystemsDevopsDeploy extends Pictogram {}
export class SystemsDevopsMonitor extends Pictogram {}
export class SystemsDevopsPlan extends Pictogram {}
export class SystemsDevopsProvision extends Pictogram {}
export class SystemsDevopsRelease extends Pictogram {}
export class SystemsDevopsTest extends Pictogram {}
export class TShirt extends Pictogram {}
export class Tags extends Pictogram {}
export class Target extends Pictogram {}
export class TargetArea extends Pictogram {}
export class TeamAlignment extends Pictogram {}
export class Teammates extends Pictogram {}
export class TelAviv extends Pictogram {}
export class Telecom extends Pictogram {}
export class Telephone extends Pictogram {}
export class Television extends Pictogram {}
export class TemperatureHigh extends Pictogram {}
export class TemperatureLow extends Pictogram {}
export class Tennis extends Pictogram {}
export class TestTubes extends Pictogram {}
export class TextToSpeech extends Pictogram {}
export class Time extends Pictogram {}
export class TimePlot extends Pictogram {}
export class TimeLapse extends Pictogram {}
export class Toggle extends Pictogram {}
export class TokyoCherryBlossom extends Pictogram {}
export class TokyoGates extends Pictogram {}
export class TokyoTemple extends Pictogram {}
export class TokyoVolcano extends Pictogram {}
export class ToneAnalyzer extends Pictogram {}
export class Tools extends Pictogram {}
export class Tornado extends Pictogram {}
export class Toronto extends Pictogram {}
export class Touch extends Pictogram {}
export class TouchGesture extends Pictogram {}
export class TouchId extends Pictogram {}
export class TouchScreen extends Pictogram {}
export class TouchSwipe extends Pictogram {}
export class Tractor extends Pictogram {}
export class TradeoffAnalytics extends Pictogram {}
export class Train extends Pictogram {}
export class TransactionalBlockchain extends Pictogram {}
export class TransactionalTrust extends Pictogram {}
export class Transform extends Pictogram {}
export class Transparency_01 extends Pictogram {}
export class Transparency_02 extends Pictogram {}
export class Trash extends Pictogram {}
export class TreeDiagram extends Pictogram {}
export class TreeMap extends Pictogram {}
export class Trousers extends Pictogram {}
export class Trust extends Pictogram {}
export class University extends Pictogram {}
export class Unlock extends Pictogram {}
export class UnlockAlt extends Pictogram {}
export class Upload extends Pictogram {}
export class UploadAlt extends Pictogram {}
export class User extends Pictogram {}
export class UserAnalytics extends Pictogram {}
export class UserInsights extends Pictogram {}
export class UserInterface extends Pictogram {}
export class UserProfile extends Pictogram {}
export class UserSearch extends Pictogram {}
export class Vancouver extends Pictogram {}
export class Video extends Pictogram {}
export class VideoAlt extends Pictogram {}
export class VideoChat extends Pictogram {}
export class VideoPlay extends Pictogram {}
export class Virus extends Pictogram {}
export class Vision extends Pictogram {}
export class VisualInsights extends Pictogram {}
export class VisualRecognition extends Pictogram {}
export class Warning extends Pictogram {}
export class WarningAlt extends Pictogram {}
export class Washer extends Pictogram {}
export class WashingtonDc extends Pictogram {}
export class WashingtonDcCapitol extends Pictogram {}
export class WashingtonDcMonument extends Pictogram {}
export class WatsonAvatar extends Pictogram {}
export class Weather extends Pictogram {}
export class WebDeveloper extends Pictogram {}
export class Webcast extends Pictogram {}
export class Wheat extends Pictogram {}
export class Wifi extends Pictogram {}
export class WindPower extends Pictogram {}
export class Windows extends Pictogram {}
export class Windy extends Pictogram {}
export class Wine extends Pictogram {}
export class WirelessHome extends Pictogram {}
export class WirelessModem extends Pictogram {}
export class WordCloud extends Pictogram {}
export class WreckingBall extends Pictogram {}
export class XRay_01 extends Pictogram {}
export class XRay_02 extends Pictogram {}
export class Yoga_01 extends Pictogram {}
export class Yoga_02 extends Pictogram {}
export class Yoga_03 extends Pictogram {}
export class Yoga_04 extends Pictogram {}
